/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/J8Hd0gKGZXf
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Header } from "@/components/layout/Header"
import { Footer } from "@/components/layout/Footer"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { FlightsTab } from "@/components/tabs/FlightsTab"
import { ExperiencesTab } from "@/components/tabs/ExperiencesTab"
import { CarsTab } from "@/components/tabs/CarsTab"
import { InsightsTab } from "@/components/tabs/InsightsTab"
import { HotelsTab } from "@/components/tabs/HotelsTab"
import { ItineraryTab } from "@/components/tabs/ItineraryTab"
import { FaPlane, FaGlobe, FaCar, FaChartBar, FaHotel, FaClipboardList } from 'react-icons/fa'

export function LandingPage() {
  return (
    <div className="relative flex flex-col min-h-screen">
      <div className="absolute top-0 left-0 right-0 h-[30vh] bg-primary"></div>
      <div className="relative flex flex-col min-h-screen">
        <Header />
        <main className="flex-1 py-10">
          <div className="container mx-auto">
            <div className="grid gap-4">
              <h1 className="text-3xl font-bold text-center text-primary-foreground">Book Your Dream Destination</h1>
            </div>
            <div className="max-w-4xl mx-auto p-6 sm:p-8 md:p-10 bg-white rounded-lg ">
              <Tabs defaultValue="flights">
                <TabsList className="flex justify-center border-b border-muted">
                  <TabsTrigger value="flights" className="flex items-center gap-2">
                    <FaPlane /> Flights
                  </TabsTrigger>
                  <TabsTrigger value="experiences" className="flex items-center gap-2 ">
                    <FaGlobe /> Experiences
                  </TabsTrigger>
                  <TabsTrigger value="cars" className="flex items-center gap-2 ">
                    <FaCar /> Cars & Transfers
                  </TabsTrigger>
                  <TabsTrigger value="insights" className="flex items-center gap-2 ">
                    <FaChartBar /> Market Insights
                  </TabsTrigger>
                  <TabsTrigger value="hotels" className="flex items-center gap-2 ">
                    <FaHotel /> Hotels
                  </TabsTrigger>
                  <TabsTrigger value="itinerary" className="flex items-center gap-2 ">
                    <FaClipboardList /> Itinerary
                  </TabsTrigger>
                </TabsList>
                <TabsContent value="flights">
                  <FlightsTab />
                </TabsContent>
                <TabsContent value="experiences">
                  <ExperiencesTab />
                </TabsContent>
                <TabsContent value="cars">
                  <CarsTab />
                </TabsContent>
                <TabsContent value="insights">
                  <InsightsTab />
                </TabsContent>
                <TabsContent value="hotels">
                  <HotelsTab />
                </TabsContent>
                <TabsContent value="itinerary">
                  <ItineraryTab />
                </TabsContent>
              </Tabs>
            </div>
          </div>
        </main>
        <Footer />
      </div>
    </div>
  )
}
